apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scanner-crb
subjects:
  - kind: ServiceAccount
    name: pantheon-scanner-sa   # prefixed service account name
    namespace: pantheon-scanner # hard-coded namespace of service-account
roleRef:
  kind: ClusterRole
  name: pantheon-scanner-cr
  apiGroup: rbac.authorization.k8s.io