apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scanner-cr
rules:
  - apiGroups: [ "" ]
    verbs: ["watch", "list", "get"]
    # a list of resource types to scan.
    resources:
      - pods
      - services
      - namespaces
      - replicationcontrollers
      - nodes
      - configmaps
      - endpoints
      - events
      - limitranges
      - persistentvolumeclaims
      - podtemplates
      - resourcequotas
      - serviceaccounts
      - componentstatuses
      - persistentvolumes
      - secrets
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - clusterroles
      - roles
      - clusterrolebindings
      - rolebindings
  - apiGroups: [ "batch" ]
    verbs: ["watch", "list", "get"]
    resources:
      - cronjobs
      - jobs
  - apiGroups: [ "apps" ]
    verbs: ["watch", "list", "get"]
    resources:
      - replicasets
      - daemonsets
      - deployments
      - statefulsets
      - controllerrevisions
      - networkpolicies
  - apiGroups: [ "networking.k8s.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - ingresses
      - networkpolicies
      - ingressclasses
  - apiGroups: [ "apps.openshift.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - deploymentconfigs
  - apiGroups: [ "argoproj.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - rollouts
  - apiGroups: [ "gateway.solo.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - gateways
      - httpgateways
      - routeoptions
      - routetables
      - virtualhostoptions
      - virtualservices
  - apiGroups: [ "getambassador.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - consulresolvers
      - devportals
      - hosts
      - kubernetesendpointresolvers
      - kubernetesserviceresolvers
      - listeners
      - logservices
      - mappings
      - modules
      - ratelimitservices
      - tcpmappings
      - tracingservices
  - apiGroups: [ "gloo.solo.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - proxies
      - upstreamgroups
      - upstreams
  - apiGroups: [ "graphql.gloo.solo.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - graphqlschemas
  - apiGroups: [ "install.istio.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - istiooperators
  - apiGroups: [ "networking.gke.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - managedcertificates
      - serviceattachments
      - frontendconfigs
      - servicenetworkendpointgroups
      - redirectservices
      - dataplanev2encryption
      - networkloggings
      - remotenodes
      - egressnatpolicies
      - gkenetworkparamsets
      - networks
  - apiGroups: [ "networking.istio.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - destinationrules
      - envoyfilters
      - gateways
      - serviceentries
      - sidecars
      - virtualservices
      - workloadentries
      - workloadgroups
  - apiGroups: [ "ratelimit.solo.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - ratelimitconfigs
  - apiGroups: [ "security.istio.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - authorizationpolicies
      - peerauthentications
      - requestauthentications
  - apiGroups: [ "storage.k8s.io" ] 
    verbs: ["watch", "list", "get"]
    resources:
      - csistoragecapacities
      - csidrivers
      - csinodes
      - storageclasses
      - volumeattachments
  - apiGroups: [ "snapshot.storage.k8s.io" ] 
    verbs: ["watch", "list", "get"]
    resources:
      - volumesnapshots
      - volumesnapshotclasses
      - volumesnapshotcontents
  - apiGroups: [ "scheduling.k8s.io" ] 
    verbs: ["watch", "list", "get"]
    resources:
      - priorityclasses
  - apiGroups: [ "cilium.io" ] 
    verbs: ["watch", "list", "get"]
    resources:
      - ciliumexternalworkloads
      - ciliumidentities
      - ciliumnodes
      - ciliumendpointslices
      - ciliumendpoints
      - ciliumlocalredirectpolicies
  - apiGroups: [ "monitoring.googleapis.com" ] 
    verbs: ["watch", "list", "get"]
    resources:
      - clusternodemonitorings
      - clusterpodmonitorings
      - clusterrules
      - globalrules
      - operatorconfigs
      - podmonitorings
      - rules
  - apiGroups: [ "cloud.google.com" ] 
    verbs: ["watch", "list", "get"]
    resources:
      - computeclasses
      - backendconfigs
  - apiGroups: [ "apiregistration.k8s.io" ] 
    verbs: ["watch", "list", "get"]
    resources:
      - apiservices
  - apiGroups: [ "flowcontrol.apiserver.k8s.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - flowschemas
      - prioritylevelconfigurations
  - apiGroups: [ "node.gke.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - gcpresourceallowlists
  - apiGroups: [ "warden.gke.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - audits
  - apiGroups: [ "admissionregistration.k8s.io"]
    verbs: ["watch", "list", "get"]
    resources:
      - mutatingwebhookconfigurations
      - validatingadmissionpolicies
      - validatingadmissionpolicybindings
      - validatingwebhookconfigurations
  - apiGroups: [ "metrics.k8s.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - pods
      - nodes
  - apiGroups: [ "autoscaling" ]
    verbs: ["watch", "list", "get"]
    resources:
      - horizontalpodautoscalers
  - apiGroups: [ "autoscaling.gke.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - multidimpodautoscalers
      - verticalpodautoscalercheckpoints
      - verticalpodautoscalers
      - horizontalpodautoscalers
  - apiGroups: [ "autoscaling.k8s.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - verticalpodautoscalercheckpoints
      - verticalpodautoscalers
      - horizontalpodautoscalers
  - apiGroups: [ "coordination.k8s.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - leases
  - apiGroups: [ "autoscaling.x-k8s.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - provisioningrequests
  - apiGroups: [ "policy" ]
    verbs: ["watch", "list", "get"]
    resources:
      - poddisruptionbudgets
  - apiGroups: [ "nodemanagement.gke.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - updateinfos
  - apiGroups: [ "nodemanagement.gke.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - updateinfos
  - apiGroups: [ "hub.gke.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - memberships
  - apiGroups: [ "internal.autoscaling.gke.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - capacityrequests
  - apiGroups: [ "events.k8s.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - events
  - apiGroups: [ "discovery.k8s.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - endpointslices
  - apiGroups: [ "auto.gke.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - allowlistedv2workloads
      - allowlistedworkloads
      - workloadallowlists
  - apiGroups: [ "apiextensions.k8s.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - customresourcedefinitions
  - apiGroups: [ "node.k8s.io" ]
    verbs: ["watch", "list", "get"]
    resources:
      - runtimeclasses
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
    verbs:
      - get
      - create
      - list
      - watch
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests/status
    verbs:
      - update
  - apiGroups:
      - certificates.k8s.io
    resources:
      - signers
    resourceNames:
      - kubernetes.io/kube-apiserver-client
    verbs:
      - sign
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests/approval
    verbs:
      - update
  - apiGroups:
      - certificates.k8s.io
    resources:
      - signers
    resourceNames:
      - kubernetes.io/kube-apiserver-client
    verbs:
      - approve